#!/bin/sh

UTOPIA_PATH="/etc/utopia/service.d"
TAD_PATH="/usr/ccsp/tad"

if [ -f /etc/device.properties ]
then
    source /etc/device.properties
fi

source $TAD_PATH/corrective_action.sh
source $UTOPIA_PATH/log_env_var.sh
exec 3>&1 4>&2 >>$SELFHEALFILE 2>&1

arping -I $SOURCE_ARPING_INTF $PEER_ARPING_IP -c 3 > /tmp/.arpingresult

arpingSuccess=`cat /tmp/.arpingresult | tail -n1 | grep "reply"`

if [ "$arpingSuccess" != "" ]
then
    isSuccess=`echo $arpingSuccess | cut -f2 -d" "`
    if [ "$isSuccess" != "" ]
    then
        if [ $isSuccess -gt 0 ]
        then
            echo "[`getDateTime`] ARPING_FROM_SOURCE:Success"
        else
            echo "[`getDateTime`] ARPING_FROM_SOURCE:Failed 0 Reply"
        fi
    else
        echo "[`getDateTime`] ARPING_FROM_SOURCE:Failed no count"
    fi
else
   echo "[`getDateTime`] ARPING_FROM_SOURCE:Failed no Reply"
fi

rm -rf /tmp/.arpingresult
